# Generated by Django 5.2.5 on 2025-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securityquestion_user_security_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, help_text='เก็บเป็น plain text', max_length=255),
        ),
    ]
