# Generated by Django 5.2.5 on 2025-09-09 07:56

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='url_source',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_upload_to),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
