# Generated by Django 5.2.5 on 2025-09-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_th',
        ),
    ]
