# Generated by Django 5.2.5 on 2025-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pendingcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='PromptPay', max_length=100)),
                ('account_name', models.CharField(default='AJ Shoes Store', max_length=200)),
                ('account_number', models.CharField(default='0912345678', max_length=50)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='pendingcheckout',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pendingcheckout',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='pendingcheckout',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=16),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='PendingCheckout',
        ),
    ]
