# Generated by Django 5.2.5 on 2025-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentconfig_remove_orderpayment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending_payment', max_length=16),
        ),
    ]
