# Generated by Django 5.2.5 on 2025-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_review_updated_at_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'รอชำระเงิน'), ('payment_verified', 'ยืนยันการชำระแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ส่งถึงแล้ว')], default='pending_payment', max_length=16),
        ),
    ]
